<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lihat Detail_MuiPaper-root jss105 MuiPa_1548a6</name>
   <tag></tag>
   <elementGuidId>fd092a49-8adf-458e-b05c-0aacc57c69f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiPaper-root.jss105.MuiPaper-elevation1.MuiPaper-rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[5]/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d655579-98e9-41ba-b1fe-dde37abc8121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root jss105 MuiPaper-elevation1 MuiPaper-rounded</value>
      <webElementGuid>d244b953-58d9-446c-a1b5-90fadf3d4494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss3 jss1&quot;]/div[@class=&quot;MuiBox-root jss23 jss2&quot;]/div[@class=&quot;MuiBox-root jss24&quot;]/div[1]/div[5]/div[1]/div[@class=&quot;MuiBox-root jss108 jss94&quot;]/div[@class=&quot;MuiBox-root jss109 jss98&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root jss99 MuiGrid-item MuiGrid-grid-xs-6&quot;]/div[@class=&quot;MuiPaper-root jss105 MuiPaper-elevation1 MuiPaper-rounded&quot;]</value>
      <webElementGuid>aedc49d4-11bf-4b4c-855f-c19ad0bbbd5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[5]/div/div/div/div/div[2]/div</value>
      <webElementGuid>88f28bae-1f60-49df-933f-daaf2a1be07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[10]/following::div[29]</value>
      <webElementGuid>aecc1bb0-1047-48ba-a6f8-fd7c3e09c884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bandung'])[4]/following::div[29]</value>
      <webElementGuid>916bef8a-15e4-441e-8711-45b0e5b2078d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[11]/preceding::div[42]</value>
      <webElementGuid>9a01e92a-24e5-48ca-8ef9-dba8b5286953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[12]/preceding::div[47]</value>
      <webElementGuid>add3c2af-e8f2-456b-b5be-8a7fd2140772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div</value>
      <webElementGuid>999df9d4-a649-4c7d-baea-b04cde2956e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
