<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hr_Jalur Khusus_MuiDivider-root jss40</name>
   <tag></tag>
   <elementGuidId>fbb4bffe-51fe-4078-8483-03840ab03ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>hr.MuiDivider-root.jss40</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div/hr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>hr</value>
      <webElementGuid>d262b84d-66b9-46e4-903c-da1dfe36e934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDivider-root jss40</value>
      <webElementGuid>64e2daba-baf4-4ba5-993d-ad15b7a67f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss3 jss1&quot;]/div[@class=&quot;MuiBox-root jss23 jss2&quot;]/div[@class=&quot;MuiBox-root jss24&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;MuiBox-root jss50 jss37&quot;]/hr[@class=&quot;MuiDivider-root jss40&quot;]</value>
      <webElementGuid>63ef67e7-fe49-47b6-9ab0-85e9b6921518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/hr</value>
      <webElementGuid>c9315a95-9e4a-4c64-b4fe-ba8171941589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hr</value>
      <webElementGuid>74b41436-684b-4366-92ac-5380c8030f21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
