<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hr_Jalur Khusus_MuiDivider-root jss64</name>
   <tag></tag>
   <elementGuidId>bd9cfb58-178b-48d3-aef4-05a34142c29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>hr.MuiDivider-root.jss64</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[4]/div/div/hr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>hr</value>
      <webElementGuid>b35e51fa-2958-4d0c-9a85-5310655bfd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDivider-root jss64</value>
      <webElementGuid>408a43ef-0861-482b-b971-608a18837d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss3 jss1&quot;]/div[@class=&quot;MuiBox-root jss23 jss2&quot;]/div[@class=&quot;MuiBox-root jss24&quot;]/div[1]/div[4]/div[1]/div[@class=&quot;MuiBox-root jss76 jss61&quot;]/hr[@class=&quot;MuiDivider-root jss64&quot;]</value>
      <webElementGuid>2d4ec7da-84ee-4988-ab64-12f3d1fc58cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[4]/div/div/hr</value>
      <webElementGuid>e630f222-849c-49e3-a4f3-c6d94c45a68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/hr</value>
      <webElementGuid>db4e659b-19ab-4e55-b67e-17c3a1afb4f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
