<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Jalur Khusus_jss58</name>
   <tag></tag>
   <elementGuidId>9ca23501-67b8-434f-b14c-bb191aafc54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.jss58</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[3]/div/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>11f75f43-b232-4c1b-b3cb-e17320b7d0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Video</value>
      <webElementGuid>3b7ea535-cf93-4528-a6d2-ca604b019116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss58</value>
      <webElementGuid>da0ac0e6-59f9-4d52-ad8b-d76f2ec6b22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/JmWE_Tfe1C8</value>
      <webElementGuid>2260de1b-6ebb-445a-a66c-1325c1ea4867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f571e6f7-79d1-4f74-aa9a-460581620f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer, autoplay; encrypted-media; gyroscope; picture-in-picture</value>
      <webElementGuid>bd9da861-e6b7-4395-a8c4-619ff7043c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss3 jss1&quot;]/div[@class=&quot;MuiBox-root jss23 jss2&quot;]/div[@class=&quot;MuiBox-root jss24&quot;]/div[1]/div[3]/div[1]/div[@class=&quot;MuiBox-root jss59 jss51&quot;]/div[@class=&quot;MuiBox-root jss60 jss55&quot;]/iframe[@class=&quot;jss58&quot;]</value>
      <webElementGuid>4bf52d38-6972-4087-9982-67cbda65080d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[3]/div/div/div/iframe</value>
      <webElementGuid>2be388da-b0fe-494f-bd9b-36c0ee32b04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>67a2cc60-a1a7-4847-a110-a9d6650c9da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Video' and @src = 'https://www.youtube.com/embed/JmWE_Tfe1C8']</value>
      <webElementGuid>09e33af9-7705-4110-baec-1a0874febc09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
