<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lihat Detail_jss132</name>
   <tag></tag>
   <elementGuidId>70a50ca2-6ecc-4635-8476-48204dc89fb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.jss132</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[7]/div/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6ca10048-e765-4221-b78d-d19e0bc5bbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Video</value>
      <webElementGuid>de2f418f-af42-406b-bd06-adfe9efa53e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss132</value>
      <webElementGuid>17692d6c-bc37-499d-9c47-c68197ff7127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/gvoceoet-I8?ab_channel=bankbjbsyariahofficial</value>
      <webElementGuid>d83f1c4a-75d4-4a42-8e92-97d41c91c5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f0c9513-b3e6-4333-9a32-38dfeba7a6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer, autoplay; encrypted-media; gyroscope; picture-in-picture</value>
      <webElementGuid>80375d10-be8f-41ea-a455-c0a2e8232f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss3 jss1&quot;]/div[@class=&quot;MuiBox-root jss23 jss2&quot;]/div[@class=&quot;MuiBox-root jss24&quot;]/div[1]/div[7]/div[1]/div[@class=&quot;MuiBox-root jss133 jss125&quot;]/div[@class=&quot;MuiBox-root jss134 jss129&quot;]/iframe[@class=&quot;jss132&quot;]</value>
      <webElementGuid>b0e944f1-1b93-474a-9ceb-fbdb8a7b13be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[7]/div/div/div/iframe</value>
      <webElementGuid>515bc272-53ac-4096-ab14-8ae750b684d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/iframe</value>
      <webElementGuid>479f7c39-eec8-4d83-96fa-e90bc48f521c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Video' and @src = 'https://www.youtube.com/embed/gvoceoet-I8?ab_channel=bankbjbsyariahofficial']</value>
      <webElementGuid>515cf7d7-3774-40c8-9ccb-e1a84a1da57e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
